"""
export_test_tensor.py

Loads a single sample from the HAR validation set, reshapes it to [1, 10, 57],
and writes a Rust source file containing:
  - pub fn input_tensor()   -> Tensor<Backend, 3>   (shape [1, 10, 57])
  - pub fn expected_label() -> usize
"""

import numpy as np
import torch
import textwrap
from pathlib import Path
from .data import load_har_data

# ── Configuration ──────────────────────────────────────────────────────────────
DATASET_DIR = "./data"
SAMPLE_INDEX = 0  # which validation sample to export
OUT_SHAPE = (1, 10, 57)  # target Burn tensor shape  (N, T, F) → 10 * 57 = 570
RAW_FEATURES = 561  # UCI-HAR raw feature width
RANDOM_SEED  = 0         # fix seed so val_ds membership is deterministic
OUT_FILE = Path("./src/data/test_tensor.rs")

# ── Load dataset ───────────────────────────────────────────────────────────────
_, val_ds, _ = load_har_data(DATASET_DIR)

# val_ds is expected to be a list/dataset of (features_tensor, label) pairs.
# Adjust the unpacking below if your dataset returns a different structure.
sample_features, sample_label = val_ds[SAMPLE_INDEX]


HAR_CLASSES = [
    "WALKING",            # 0
    "WALKING_UPSTAIRS",   # 1
    "WALKING_DOWNSTAIRS", # 2
    "SITTING",            # 3
    "STANDING",           # 4
    "LAYING",             # 5
]

# ── Extract sample ─────────────────────────────────────────────────────────────
x, y = val_ds[SAMPLE_INDEX]          # x: [10, 57],  y: scalar tensor
x_export = x.unsqueeze(0)            # [1, 10, 57]
# x_export = x
label: int = int(y.item())           # 0-indexed (0-5)

assert x_export.shape == (1, 10, 57), f"Unexpected shape: {x_export.shape}"
assert 0 <= label <= 5,               f"Label out of range: {label}"

# ── Format flat f32 array as a Rust literal ────────────────────────────────────
flat = x_export.numpy().flatten()    # length 570

VALUES_PER_LINE = 8

def fmt_f32(v: float) -> str:
    return f"{v:.8e}_f32"

rows = []
for i in range(0, len(flat), VALUES_PER_LINE):
    chunk = flat[i : i + VALUES_PER_LINE]
    rows.append("        " + ", ".join(fmt_f32(v) for v in chunk))
data_literal = ",\n".join(rows)

N, T, F_ = x_export.shape   # 1, 10, 57
total     = N * T * F_       # 570

# ── Render Rust source ─────────────────────────────────────────────────────────
label_name = HAR_CLASSES[label]

rust_src = f"""\
//! Auto-generated by export_test_tensor.py -- do not edit by hand.
//!
//! Validation sample index : {SAMPLE_INDEX}
//! Tensor shape            : [{N}, {T}, {F_}]
//! Padding                 : 561 raw features -> {total} (9 zeros appended)
//! Label                   : {label}  ({label_name}, 0-indexed)
//! Val-split seed          : {RANDOM_SEED}

use burn::{{
    backend::NdArray,
    tensor::Tensor,
}};

type Backend = NdArray<f32>;


/// Test input tensor of shape `[{N}, {T}, {F_}]`.
///
/// Derived from UCI-HAR validation sample {SAMPLE_INDEX} via the same pipeline
/// used in training:
///   1. Load raw 561-feature row from `X_train.txt`
///   2. Zero-pad to {total}, reshape to `[{N}, {T}, {F_}]`
///   3. Split off validation set (seed {RANDOM_SEED}), pick index {SAMPLE_INDEX}
pub fn input_tensor() -> Tensor<Backend, 3> {{
    #[rustfmt::skip]
    let data: [f32; {total}] = [
{data_literal}
    ];

    Tensor::<Backend, 1>::from_floats(data, &Default::default())
        .reshape([{N}, {T}, {F_}])
}}

/// Expected activity label for the exported sample (0-indexed, 0-5).
///
/// | Value | Activity              |
/// |-------|-----------------------|
/// |   0   | WALKING               |
/// |   1   | WALKING_UPSTAIRS      |
/// |   2   | WALKING_DOWNSTAIRS    |
/// |   3   | SITTING               |
/// |   4   | STANDING              |
/// |   5   | LAYING                |
///
/// Ground truth for this sample: `{label}` ({label_name})
pub fn expected_label() -> usize {{
    {label}_usize
}}
"""

# ── Write output ───────────────────────────────────────────────────────────────
OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
OUT_FILE.write_text(rust_src, encoding="utf-8")

print(f"✓  Exported val_ds[{SAMPLE_INDEX}]")
print(f"   shape  : {list(x_export.shape)}")
print(f"   label  : {label} ({label_name})")
print(f"   output : {OUT_FILE}")
