"""
kws_to_burn_tensor.py

Loads a single sample from the KWS validation set, reshapes it to [1, 101, 40],
and writes a Rust source file containing:
  - pub fn input_tensor()   -> Tensor<Backend, 3>   (shape [1, 101, 40])
  - pub fn expected_label() -> usize
"""

import torch
from pathlib import Path
from .data import load_speechcommands_data, CLASSES

# ── Configuration ──────────────────────────────────────────────────────────────
DATASET_DIR  = "./data"
SAMPLE_INDEX = 0          # which validation sample to export
OUT_SHAPE    = (1, 51, 40)  # target Burn tensor shape  (N, T, F)
RANDOM_SEED  = 0          # fix seed so val_ds membership is deterministic
OUT_FILE     = Path("./src/data/test_tensor.rs")

# ── Populate with your keyword class names in index order ──────────────────────
KWS_CLASSES = CLASSES

# ── Load dataset ───────────────────────────────────────────────────────────────
_, val_ds, _ = load_speechcommands_data(DATASET_DIR)

# val_ds is expected to be a list/dataset of (features_tensor, label) pairs.
# Adjust the unpacking below if your dataset returns a different structure.

# ── Extract sample ─────────────────────────────────────────────────────────────
x, y = val_ds[SAMPLE_INDEX]     # x: [101, 40],  y: scalar tensor
x_export = x.unsqueeze(0)       # [1, 101, 40]
label: int = y      # 0-indexed

assert x_export.shape == torch.Size(OUT_SHAPE), \
    f"Unexpected shape: {x_export.shape}, expected {OUT_SHAPE}"
if KWS_CLASSES:
    assert 0 <= label < len(KWS_CLASSES), f"Label out of range: {label}"

# ── Format flat f32 array as a Rust literal ────────────────────────────────────
flat = x_export.numpy().flatten()    # length 4040

VALUES_PER_LINE = 8

def fmt_f32(v: float) -> str:
    return f"{v:.8e}_f32"

rows = []
for i in range(0, len(flat), VALUES_PER_LINE):
    chunk = flat[i : i + VALUES_PER_LINE]
    rows.append("        " + ", ".join(fmt_f32(v) for v in chunk))
data_literal = ",\n".join(rows)

N, T, F_ = x_export.shape       # 1, 101, 40
total     = N * T * F_           # 4040

# ── Render Rust source ─────────────────────────────────────────────────────────
label_name = KWS_CLASSES[label] if KWS_CLASSES else str(label)

rust_src = f"""\
//! Auto-generated by kws_to_burn_tensor.py -- do not edit by hand.
//!
//! Validation sample index : {SAMPLE_INDEX}
//! Tensor shape            : [{N}, {T}, {F_}]
//! Label                   : {label}  ({label_name}, 0-indexed)
//! Val-split seed          : {RANDOM_SEED}

use burn::{{
    backend::NdArray,
    tensor::Tensor,
}};

type Backend = NdArray<f32>;


/// Test input tensor of shape `[{N}, {T}, {F_}]`.
///
/// Derived from KWS validation sample {SAMPLE_INDEX} via the same pipeline
/// used in training:
///   1. Load raw MFCC features from the dataset
///   2. Reshape to `[{N}, {T}, {F_}]`
///   3. Split off validation set (seed {RANDOM_SEED}), pick index {SAMPLE_INDEX}
pub fn input_tensor() -> Tensor<Backend, 3> {{
    #[rustfmt::skip]
    let data: [f32; {total}] = [
{data_literal}
    ];

    Tensor::<Backend, 1>::from_floats(data, &Default::default())
        .reshape([{N}, {T}, {F_}])
}}

/// Expected keyword label for the exported sample (0-indexed).
///
/// Ground truth for this sample: `{label}` ({label_name})
pub fn expected_label() -> usize {{
    {label}_usize
}}
"""

# ── Write output ───────────────────────────────────────────────────────────────
OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
OUT_FILE.write_text(rust_src, encoding="utf-8")

print(f"✓  Exported val_ds[{SAMPLE_INDEX}]")
print(f"   shape  : {list(x_export.shape)}")
print(f"   label  : {label} ({label_name})")
print(f"   output : {OUT_FILE}")
