"""
Transform an MNIST image into a Burn `Tensor<Backend, 4>` compatible format.

Pipeline:
  1. Load MNIST via torchvision (PyTorch dataset).
  2. Apply standard pre-processing (ToTensor + Normalize).
  3. Add the batch dimension → shape [1, 1, 28, 28]  (N, C, H, W).
  4. Export the raw float32 data so Burn can consume it:
       • a .npy file  (load with burn-import / ndarray feature)
       • a .bin file  (load with TensorData::from_bytes)
       • an inline Rust snippet printed to stdout
"""

import struct
import numpy as np
import torch
from torchvision import datasets, transforms


# ── 1. Dataset & transform ────────────────────────────────────────────────────

transform = transforms.Compose(
    [
        # [0,255] uint8 → [0.0,1.0] float32, shape (C,H,W)
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,)),  # standard MNIST mean / std
    ]
)

mnist = datasets.MNIST(
    root="../Datasets/",
    train=False,  # use the test split (no training needed for inference)
    download=True,
    transform=transform,
)


# ── 2. Pick one sample ────────────────────────────────────────────────────────

sample_index = 2
image_tensor, label = mnist[sample_index]  # shape: (1, 28, 28) — C, H, W

print(f"Sample index : {sample_index}")
print(f"Label        : {label}")
print(f"Tensor shape : {image_tensor.shape}")  # torch.Size([1, 28, 28])
print(f"dtype        : {image_tensor.dtype}")
print(f"min / max    : {image_tensor.min():.4f} / {image_tensor.max():.4f}")


# ── 3. Add batch dimension → Tensor<Backend, 4>  [N, C, H, W] ────────────────

burn_tensor: torch.Tensor = image_tensor.unsqueeze(0)  # (1, 1, 28, 28)
print(f"\nBurn-ready shape [N,C,H,W]: {list(burn_tensor.shape)}")


# ── 4a. Export as NumPy (.npy) — usable with burn-import ─────────────────────

# npy_path = "mnist_sample.npy"
# np_array: np.ndarray = burn_tensor.numpy()   # shape (1,1,28,28), dtype float32
# np.save(npy_path, np_array)
# print(f"\nSaved .npy  → {npy_path}  shape={np_array.shape}  dtype={np_array.dtype}")


# ── 4b. Export as raw little-endian float32 binary ───────────────────────────

# bin_path = "mnist_sample.bin"
# flat: np.ndarray = np_array.flatten()
# with open(bin_path, "wb") as fh:
#     fh.write(struct.pack(f"<{len(flat)}f", *flat.tolist()))
# print(f"Saved .bin  → {bin_path}  ({len(flat)} float32 values, {len(flat)*4} bytes)")


# ── 4c. Emit a Rust snippet using from_floats (no vec!, no_std compatible) ───
#
# from_floats() accepts a *nested array literal* whose nesting depth matches
# the tensor rank.  For Tensor<Backend, 4> with shape [N, C, H, W] = [1,1,28,28]
# the literal must be [[[[f32; 28]; 28]; 1]; 1], i.e. four levels of brackets.
#
# Layout built here:
#   pixel_rows  – one &str per row:   "v0, v1, … v27"
#   pixel_grid  – 28 rows wrapped:    "[row0], [row1], … [row27]"
#   channel     – single channel:     "[pixel_grid]"
#   batch       – single image:       "[channel]"

N, C, H, W = 1, 1, 28, 28
values_4d = burn_tensor.numpy()  # shape (1,1,28,28)


def fmt(v: float) -> str:
    return f"{v:.6f}_f32"


# Build the nested literal bottom-up: row → height → channel → batch
rows = []
for h in range(H):
    row_vals = ", ".join(fmt(values_4d[0, 0, h, w]) for w in range(W))
    rows.append(f"[{row_vals}]")

pixel_grid = ",\n            ".join(rows)  # 28 rows, indented nicely
channel_lit = f"[\n            {pixel_grid}\n        ]"
batch_lit = f"[\n        {channel_lit}\n    ]"
full_lit = f"[\n    {batch_lit}\n]"

rust_snippet = f"""// ── Rust / Burn snippet (no_std compatible) ──────────────────────────────────
// Cargo.toml:
//   burn = {{ version = "0.14", default-features = false, features = ["ndarray"] }}
//
// from_floats() takes a nested array literal; no vec!, no alloc required for
// constructing the literal itself.

extern crate alloc;

use burn::{{
    backend::NdArray,
    tensor::Tensor,
}};

type Backend = NdArray<f32>;

pub fn input_tensor() -> Tensor<Backend, 4> {{
    // Shape: [N=1, C=1, H=28, W=28]
    // Generated by mnist_to_burn_tensor.py — label {label}
    Tensor::<Backend, 4>::from_floats(
        {full_lit},
        &Default::default(),
    )
}}
"""

print(rust_snippet)

rs_path = "src/data/mnist_tensor.rs"
with open(rs_path, "w") as fh:
    fh.write(rust_snippet.strip())
print(f"Saved Rust snippet → {rs_path}")
